version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  info_file_handler:
    #不同handler的配置项，参考api文档中该handler的构造函数进行配置。
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    filename: ../logs/infos.log
    when: D
    encoding: utf8
  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: ../logs/errors.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
loggers:
  mylogger:
    level: DEBUG
    handlers: [console,info_file_handler,error_file_handler]
    propagate: no
root:
  level: DEBUG
  handlers: [console]